name: OpenCart API Automation CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Print Current Directory
        run: |
          echo "Current Directory:"
          pwd
          echo "Listing Files:"
          ls -la

      - name: Find OpenCart_API_RestAssured Directory
        run: |
          find . -type d -name "OpenCart_API_RestAssured"

      - name: Move to Correct Directory
        run: |
          if [ -d "OpenCart_API_RestAssured" ]; then
            cd OpenCart_API_RestAssured
          elif [ -d "./some-other-folder/OpenCart_API_RestAssured" ]; then
            cd ./some-other-folder/OpenCart_API_RestAssured
          else
            echo "ERROR: OpenCart_API_RestAssured directory not found!"
            exit 1
          fi

      - name: Build with Maven
        run: mvn clean install
